CREATE TABLE sticker_pack (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    owner_uid INTEGER NOT NULL,
    status SMALLINT NOT NULL DEFAULT 0,
    title JSONB NOT NULL DEFAULT '{}',
    description JSONB NOT NULL DEFAULT '{}',
    preview_pid INTEGER NOT NULL DEFAULT 1,
    created TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    published_at TIMESTAMPTZ
);

CREATE INDEX sticker_pack_owner_uid_idx ON sticker_pack (owner_uid);
CREATE INDEX sticker_pack_status_idx ON sticker_pack (status);

INSERT INTO sticker_pack (id, owner_uid, status, title, preview_pid, published_at) VALUES
    (1, 2, 1, '{"zh-cn":"鲲 Galgame 表情包 [1]","en-us":"KUN Visual Novel Stickers [1]","ja-jp":"鯤 Galgame スタンプ [1]"}'::jsonb, 1, NOW()),
    (2, 2, 1, '{"zh-cn":"鲲 Galgame 表情包 [2]","en-us":"KUN Visual Novel Stickers [2]","ja-jp":"鯤 Galgame スタンプ [2]"}'::jsonb, 18, NOW()),
    (3, 2, 1, '{"zh-cn":"鲲 Galgame 表情包 [3]","en-us":"KUN Visual Novel Stickers [3]","ja-jp":"鯤 Galgame スタンプ [3]"}'::jsonb, 35, NOW()),
    (4, 2, 1, '{"zh-cn":"鲲 Galgame 表情包 [4]","en-us":"KUN Visual Novel Stickers [4]","ja-jp":"鯤 Galgame スタンプ [4]"}'::jsonb, 52, NOW()),
    (5, 2, 1, '{"zh-cn":"鲲 Galgame 表情包 [5]","en-us":"KUN Visual Novel Stickers [5]","ja-jp":"鯤 Galgame スタンプ [5]"}'::jsonb, 69, NOW()),
    (6, 2, 1, '{"zh-cn":"鲲 Galgame 表情包 [6]","en-us":"KUN Visual Novel Stickers [6]","ja-jp":"鯤 Galgame スタンプ [6]"}'::jsonb, 6, NOW()),
    (7, 2, 1, '{"zh-cn":"鲲 Galgame 表情包 [7]","en-us":"KUN Visual Novel Stickers [7]","ja-jp":"鯤 Galgame スタンプ [7]"}'::jsonb, 12, NOW());

SELECT setval(pg_get_serial_sequence('sticker_pack', 'id'), 7);

ALTER TABLE sticker
    ADD COLUMN image_hash CHAR(64);

CREATE INDEX sticker_image_hash_idx ON sticker (image_hash)
    WHERE image_hash IS NOT NULL;

ALTER TABLE sticker
    ADD CONSTRAINT sticker_sid_pack_fk
    FOREIGN KEY (sid) REFERENCES sticker_pack (id);
